### ISSUE TITLE
Use issues and issue templates instead of a PR to request a new ID

### ISSUE THREAD

**Issue by danielkhan** [w3c/tracestate-ids-registry#1]
Right now, we ask interested parties to create a PR to be included in the registry.

I would recommend using [issue templates](https://help.github.com/en/articles/creating-issue-templates-for-your-repository) for this process because it's easier, more inclusive, avoids merge conflicts and provides better tooling for discussions.

Issue templates let you create templates for different purposes. Like Addition, Deletion, Modification. Admin privileges are needed to create them.

Example:

```
---
name: Request a new ID
about: I want to add a new ID
title: Request for Inclusion
labels: 'new-id'
assignees: ''

---
**Proposed ID**
Please select an ID that is unique to the [registry](https://w3c.github.io/trace-state-ids-registry/).

**Link to a publicly available specification**
Please provide a link that references a public available specification (PAS) that defines the identifier for the tracestate header used trace context

**Contact Information**
Please provide a company name and the name and email address of the responsible individual or group.
```

**Comment by SergeyKanzhelev** [comment]
Either PR or issues would be working.

**Comment by discostu105** [comment]
Why exactly is a `**Link to a publicly available specification**` required?

I'd like to register Dynatrace, but currently we have no public spec describing our tracestate. Isn't it enough to provide the name of the key?
