### ISSUE TITLE
Rename repository to tracestate-ids-registry

### ISSUE THREAD

**Issue by SergeyKanzhelev** [w3c/tracestate-ids-registry#11]
I suggest to rename repository to tracestate-ids-registry to make sure it's clear that the tracestate is suppose to be used as a single word

**Comment by danielkhan** [comment]
I agree. 
@caribouW3 - is it possible for you to make this change? `trace-state-ids-registry` => `tracestate-ids-registry`

**Comment by caribouW3** [comment]
I renamed the repo and the github.io uri.
You can update the version links in the spec accordingly.

**Comment by basti1302** [comment]
This has happened, so closing :)
